sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "e3e7402079c30da10a611c40c60c2a22f0886995"
    token:
      secure: $SONAR_TOKEN

env:
  - NODE_VERSION=10-jessie
  - NODE_VERSION=14-alpine

cache:
  directories:
    - node_modules

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION  .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD)
  - sonar-scanner

stages:
  - test
  - npm-targets

jobs:
  include:
    - stage: npm-targets
      name: "Test 14-alpine"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=14-alpine
        - NPM_TARGET=test
    - stage: npm-targets
      name: "Coverage 14-alpine"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=14-alpine
        - NPM_TARGET=coverage
    - stage: npm-targets
      name: "Build 14-alpine"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=build
    - stage: npm-targets
      name: "Test 10-jessie"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=14-alpine
        - NPM_TARGET=test
    - stage: npm-targets
      name: "Coverage 10-jessie"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=coverage
    - stage: npm-targets
      name: "Build 10-jessie"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=build

notifications:
  email: false
