sudo: required

services:
  - docker

env:
  - NODE_VERSION=10-jessie
  - NODE_VERSION=14-alpine

cache:
  directories:
    - node_modules

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION  .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/rtl-demo:$NODE_VERSION-$(git rev-parse HEAD)

notifications:
  email: false
